### ISSUE TITLE
some lua keeps opening april fools and some expired discord link

### ISSUE THREAD

**Issue by gn1e** [ticzz/Aimware-v5-luas#1]

**Comment by ticzz** [comment]
When i reuploaded it i was too lazy to sortout some luas that are outdated or broken so i just put the whole folder. And i still didnt remove the files from my folder because some of them contain functions u need/could use in your own scripts and other are well documantated and everything got explaint by comments so that u can learn how things working..

Can u name the scripts u talk about so i dont need to check all files one by one..

**Comment by ticzz** [comment]
i removed all luas that contained discordlinks just to make sure that no lua in this repo will cause any malicious stuff by redirecting you to a (random or suspecting) discord server..

Better be safe than sorry.. ;D
